CREATE TABLE USUARIO (
    USUARIO_ID          NUMBER(10),
    NOMBRE              VARCHAR2(25) NOT NULL,
    APELLIDO            VARCHAR2(25) NOT NULL,
    CORREO              VARCHAR2(25) NOT NULL UNIQUE,
    CONTRASENA          VARCHAR2(25) NOT NULL,
    FCHA_RGSTRO         DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT usuario_usuario_id_pk PRIMARY KEY (USUARIO_ID)
);

CREATE TABLE PERFIL (
    USUARIO_ID          NUMBER(10),
    PERFIL_ID           NUMBER(10),
    FOTO                VARCHAR2(50),
    DIRECCION           VARCHAR2(30),
    TELEFONO            VARCHAR2(20) UNIQUE,
    
    CONSTRAINT perfil_id_pk PRIMARY KEY (USUARIO_ID, PERFIL_ID),
    CONSTRAINT perfil_usuario_id_fk FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE
);


CREATE TABLE COMPRADOR (
    COMPRADOR_ID        NUMBER(10),
    USUARIO_ID          NUMBER(10) NOT NULL,
    
    CONSTRAINT comprador_comprador_id_pk PRIMARY KEY (COMPRADOR_ID),
    CONSTRAINT comprador_usuario_id_fk FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE VENDEDOR (
    USUARIO_ID          NUMBER(10),
    VENDEDOR_ID         NUMBER(10),
    
    CONSTRAINT vededor_id_pk PRIMARY KEY (USUARIO_ID, VENDEDOR_ID),
    CONSTRAINT vededor_usuario_id_fk FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE
);

CREATE TABLE ADMINISTRADOR (
    ADMINISTRADOR_ID    NUMBER(10),
    USUARIO_ID          NUMBER(10) NOT NULL,
    
    CONSTRAINT administrador_administrador_id_pk PRIMARY KEY (ADMINISTRADOR_ID),
    CONSTRAINT administrador_usuario_id_fk FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(USUARIO_ID)
);


CREATE TABLE PRODUCTO (
    VENDEDOR_ID         NUMBER(10),
    PRODUCTO_ID         NUMBER(10),
    NOMBRE              VARCHAR2(20) NOT NULL,
    DESCRIPCION         VARCHAR2(50) NOT NULL,
    PRECIO              NUMBER(10) NOT NULL,
    FECHA               DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT producto_id_pk PRIMARY KEY (VENDEDOR_ID, PRODUCTO_ID),
    CONSTRAINT producto_vendedor_id_fk FOREIGN KEY (VENDEDOR_ID) 
        REFERENCES VENDEDOR(VENDEDOR_ID),
    CONSTRAINT producto_precio_min CHECK (PRECIO >= 0)
);

CREATE TABLE TIPO (
    TIPO_ID             NUMBER(10),
    VRSION_CMPTBLE      VARCHAR2(10) NOT NULL,
    TIPO                VARCHAR2(10) NOT NULL,
    PRODUCTO_ID         NUMBER(10) NOT NULL,
    
    CONSTRAINT tipo_tipo_id_pk PRIMARY KEY (TIPO_ID),
    CONSTRAINT tipo_producto_id_fk FOREIGN KEY (PRODUCTO_ID) 
        REFERENCES PRODUCTO(PRODUCTO_ID)
);

CREATE TABLE PLUGIN (
    TIPO_ID             NUMBER(10),
    VERSIO              NUMBER(10) NOT NULL,
    
    CONSTRAINT plugin_tipo_id_pk PRIMARY KEY (TIPO_ID),
    CONSTRAINT plugin_tipo_id_fk FOREIGN KEY (TIPO_ID) 
        REFERENCES TIPO(TIPO_ID) ON DELETE CASCADE
);

CREATE TABLE SCHEMATIC (
    TIPO_ID             NUMBER(10),
    DIMENSIONES         VARCHAR2(15) NOT NULL,
    
    CONSTRAINT schematic_tipo_id_pk PRIMARY KEY (TIPO_ID),
    CONSTRAINT schematic_tipo_id_fk FOREIGN KEY (TIPO_ID) 
        REFERENCES TIPO(TIPO_ID) ON DELETE CASCADE
);


CREATE TABLE OFERTA (
    OFERTA_ID           NUMBER(10),
    DESCUENTO           NUMBER(10) NOT NULL,
    FECHA_INICIO        DATE DEFAULT SYSDATE NOT NULL,
    FECHA_FINAL         DATE DEFAULT SYSDATE NOT NULL,
    PRODUCTO_ID         NUMBER(10) NOT NULL,
    VENDEDOR_ID         NUMBER(10) NOT NULL,
    
    CONSTRAINT oferta_oferta_id_pk PRIMARY KEY (OFERTA_ID),
    CONSTRAINT oferta_producto_id_fk FOREIGN KEY (PRODUCTO_ID) 
        REFERENCES PRODUCTO(PRODUCTO_ID),
    CONSTRAINT oferta_cendedor_id_fk FOREIGN KEY (VENDEDOR_ID) 
        REFERENCES VENDEDOR(VENDEDOR_ID)
);

CREATE TABLE NOTIFICACION (
    NOTIFICACION_ID     NUMBER(10),
    MENSAJE             VARCHAR2(50) NOT NULL,
    FECHA               DATE DEFAULT SYSDATE NOT NULL,
    USUARIO_ID          NUMBER(10) NOT NULL,
    OFERTA_ID           NUMBER(10) NOT NULL,
    
    CONSTRAINT notificacion_notificacion_id_pk PRIMARY KEY (NOTIFICACION_ID),
    CONSTRAINT notificacion_usuario_id_fk FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT notificacion_oferta_id_fk FOREIGN KEY (OFERTA_ID) 
        REFERENCES OFERTA (OFERTA_ID)
);

CREATE TABLE SOPORTE (
    SOPORTE_ID          NUMBER(10),
    MENSAJE             VARCHAR2(50) NOT NULL,
    FECHA               DATE DEFAULT SYSDATE NOT NULL,
    USUARIO_ID          NUMBER(10) NOT NULL,
    
    CONSTRAINT soporte_soporte_id_pk PRIMARY KEY (SOPORTE_ID),
    CONSTRAINT soporte_usuario_id_fk FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE RESPUESTA (
    SOPORTE_ID          NUMBER(10),
    RESPUESTA_ID        NUMBER(10),
    MENSAJE             VARCHAR2(50) NOT NULL,
    FECHA               DATE DEFAULT SYSDATE NOT NULL,
    USUARIO_ID          NUMBER(10),
    ADMINISTRADOR_ID    NUMBER(10),
    
    CONSTRAINT respuesta_id_pk PRIMARY KEY (SOPORTE_ID, RESPUESTA_ID),
    CONSTRAINT respuesta_soporte_id_fk FOREIGN KEY (SOPORTE_ID) 
        REFERENCES SOPORTE(SOPORTE_ID) ON DELETE CASCADE,
    CONSTRAINT respuesta_usuario_id_fk FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT respuesta_administrador_id_fk FOREIGN KEY (ADMINISTRADOR_ID) 
        REFERENCES ADMINISTRADOR(ADMINISTRADOR_ID)
);

CREATE TABLE LISTA_DESEO (
    USUARIO_ID          NUMBER(10),
    LISTA_DESEO_ID      NUMBER(10),
    
    CONSTRAINT lista_deseo_id_pk PRIMARY KEY (USUARIO_ID, LISTA_DESEO_ID),
    CONSTRAINT lista_deseo_usuario_id_fk FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE
);

CREATE TABLE PRDCTO_LSTA_DSEO (
    LISTA_DESEO_ID      NUMBER(10),
    PRODUCTO_ID         NUMBER(10),
    
    CONSTRAINT prdcto_lsta_dseo_id_pk PRIMARY KEY (LISTA_DESEO_ID, PRODUCTO_ID),
    CONSTRAINT prdcto_lsta_dseo_lista_deseo_id_fk FOREIGN KEY (LISTA_DESEO_ID) 
        REFERENCES LISTA_DESEO(LISTA_DESEO_ID) ON DELETE CASCADE,
    CONSTRAINT prdcto_lsta_dseo_producto_id_fk FOREIGN KEY (PRODUCTO_ID) 
        REFERENCES PRODUCTO(PRODUCTO_ID) ON DELETE CASCADE
);

CREATE TABLE VALORACION (
    COMPRADOR_ID        NUMBER(10),
    PRODUCTO_ID         NUMBER(10),
    ESTRELLAS           NUMBER(5) NOT NULL,
    COMENTARIO          VARCHAR2(20) NOT NULL,
    
    CONSTRAINT valoracion_id_pk PRIMARY KEY (COMPRADOR_ID, PRODUCTO_ID),
    CONSTRAINT valoracion_comprador_id_fk FOREIGN KEY (COMPRADOR_ID) 
        REFERENCES COMPRADOR(COMPRADOR_ID) ON DELETE CASCADE,
    CONSTRAINT valoracion_producto_id_fk FOREIGN KEY (PRODUCTO_ID) 
        REFERENCES PRODUCTO(PRODUCTO_ID) ON DELETE CASCADE
);

CREATE TABLE DESCARGA (
    COMPRADOR_ID        NUMBER(10),
    PRODUCTO_ID         NUMBER(10),
    FECHA               DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT descarga_id_pk PRIMARY KEY (COMPRADOR_ID, PRODUCTO_ID),
    CONSTRAINT descarga_comprador_id_fk FOREIGN KEY (COMPRADOR_ID) 
        REFERENCES COMPRADOR(COMPRADOR_ID) ON DELETE CASCADE,
    CONSTRAINT descarga_producto_id_fk FOREIGN KEY (PRODUCTO_ID) 
        REFERENCES PRODUCTO(PRODUCTO_ID) ON DELETE CASCADE
);

CREATE TABLE CARRITO (
    COMPRADOR_ID        NUMBER(10),
    CARRITO_ID          NUMBER(10),
    PRECIO_TOTAL        NUMBER(15) NOT NULL,
    
    CONSTRAINT carrito_id_pk PRIMARY KEY (COMPRADOR_ID, CARRITO_ID),
    CONSTRAINT carrito_comprador_id_fk FOREIGN KEY (COMPRADOR_ID) 
        REFERENCES COMPRADOR(COMPRADOR_ID) ON DELETE CASCADE
);

CREATE TABLE PRDCTO_CRRTO (
    CARRITO_ID          NUMBER(10),
    PRODUCTO_ID         NUMBER(10),
    CANTIDAD            NUMBER(20) NOT NULL,
    
    CONSTRAINT prdcto_crrto_id_pk PRIMARY KEY (CARRITO_ID, PRODUCTO_ID),
    CONSTRAINT prdcto_crrto_carrito_id_fk FOREIGN KEY (CARRITO_ID) 
        REFERENCES CARRITO(CARRITO_ID) ON DELETE CASCADE, 
    CONSTRAINT prdcto_crrto_producto_id_fk FOREIGN KEY (PRODUCTO_ID) 
        REFERENCES PRODUCTO(PRODUCTO_ID) ON DELETE CASCADE
);

CREATE TABLE METODO_PAGO (
    METODO_PAGO_ID      NUMBER(10),
    NOMBRE              VARCHAR2(20) NOT NULL,
    DESCRIPCION         VARCHAR2(20) NOT NULL,

    CONSTRAINT metodo_pago_metodo_pago_id_pk PRIMARY KEY (METODO_PAGO_ID) 
);


CREATE TABLE PAGO (
    COMPRADOR_ID        NUMBER(10),
    METODO_PAGO_ID      NUMBER(10),
    PAGO_ID             NUMBER(10),
    FECHA               DATE DEFAULT SYSDATE NOT NULL,
    TOTAL               NUMBER(10) NOT NULL,
    
    CONSTRAINT pago_id_pk PRIMARY KEY (COMPRADOR_ID, METODO_PAGO_ID, PAGO_ID),
    CONSTRAINT pago_comprador_id_fk FOREIGN KEY (COMPRADOR_ID) 
        REFERENCES COMPRADOR(COMPRADOR_ID) ON DELETE CASCADE,   
    CONSTRAINT pago_metodo_pago_id_fk FOREIGN KEY (METODO_PAGO_ID) 
        REFERENCES METODO_PAGO(METODO_PAGO_ID) ON DELETE CASCADE
);

CREATE TABLE RECIBO (
    PAGO_ID             NUMBER(10),
    RECIBO_ID           NUMBER(10),
    FECHA               DATE DEFAULT SYSDATE NOT NULL,
    COMPRADOR_ID        NUMBER(10) NOT NULL,
    CARRITO_ID          NUMBER(10) NOT NULL,
    
    CONSTRAINT recibo_id_pk PRIMARY KEY (PAGO_ID, RECIBO_ID),
    CONSTRAINT recibo_pago_id_fk FOREIGN KEY (PAGO_ID) 
        REFERENCES PAGO(PAGO_ID) ON DELETE CASCADE, 
    CONSTRAINT recibo_comprador_id_fk FOREIGN KEY (COMPRADOR_ID) 
        REFERENCES COMPRADOR(COMPRADOR_ID),    
    CONSTRAINT recibo_carrito_id_fk FOREIGN KEY (CARRITO_ID) 
        REFERENCES CARRITO(CARRITO_ID)
);

